eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: hrm-zuul-server  #指定服务的id
server:
  port: 1020
spring:
  application:
    name: hrm-zuul-server
zuul:
  ignored-services: "*"   #禁止使用服务名字进行访问
  prefix: "/hrm"  #统一的前缀
  routes: #配置路由，指定服务的访问路径
    hrm-systemmanage-service: "/system/**"
    hrm-course-service: "/course/**"
    hrm-redis-service: "/redis/**"
  retryable: true #开启重试
ribbon:
  ConnectTimeout: 2000  # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 3000 # 熔断超时时长：3000ms