#spring:
#  cloud:
#    config:
#     uri: http://localhost:1030
#     name: application-fastdfs
#     profile: dev
#     label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: hrm-fastdfs-service  #指定服务的id
server:
  port: 2050
spring:
  application:
    name: hrm-fastdfs-service